# Generated by Django 5.2.13 on 2026-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_desktop', models.ImageField(help_text='Tamaño recomendado: 1920x650 píxeles', upload_to='sliders/')),
                ('imagen_mobile', models.ImageField(help_text='Tamaño recomendado: 800x800 píxeles', upload_to='sliders/')),
                ('texto', models.TextField(help_text='Texto a mostrar sobre el slider')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
