# Generated by Django 5.2.13 on 2026-05-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(help_text='Logo de la empresa (PNG transparente recomendado)', upload_to='logos_empresas/', verbose_name='Logo')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número menor aparece primero', verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
