# Generated by Django 5.2.13 on 2026-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa / organización')),
                ('rubro', models.CharField(choices=[('agropecuario', 'Agropecuario / Rural'), ('construccion', 'Construcción / Obra'), ('gastronomia', 'Gastronomía / Hotelería'), ('industria', 'Industria / Manufactura'), ('comercio', 'Comercio / Ventas'), ('tecnologia', 'Tecnología / Sistemas'), ('salud', 'Salud / Cuidado personal'), ('educacion', 'Educación / Capacitación'), ('logistica', 'Logística / Transporte'), ('otro', 'Otro')], max_length=50, verbose_name='Rubro o sector')),
                ('localidad', models.CharField(max_length=150, verbose_name='Localidad / Zona')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre del responsable')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('perfil_buscado', models.CharField(help_text='Ej: Electricista, Cocinero, Operador de PC, etc.', max_length=250, verbose_name='¿Qué perfil profesional necesita?')),
                ('descripcion_tareas', models.TextField(verbose_name='Descripción de tareas y responsabilidades')),
                ('cantidad_personas', models.CharField(choices=[('1', '1 persona'), ('2-5', '2 a 5 personas'), ('6-10', '6 a 10 personas'), ('mas10', 'Más de 10 personas')], max_length=10, verbose_name='Cantidad de personas requeridas')),
                ('urgencia', models.CharField(choices=[('inmediata', 'Inmediata (ya lo necesito)'), ('proximos_meses', 'En los próximos 3 a 6 meses'), ('planificacion', 'Es una planificación a largo plazo')], default='proximos_meses', max_length=20, verbose_name='Urgencia')),
                ('modalidad', models.CharField(blank=True, help_text='Ej: Relación de dependencia, por hora, temporario, etc.', max_length=200, null=True, verbose_name='Modalidad de contratación')),
                ('condiciones_adicionales', models.TextField(blank=True, null=True, verbose_name='Requisitos o condiciones adicionales')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas internas (solo admins)')),
            ],
            options={
                'verbose_name': 'Interés de Empresa',
                'verbose_name_plural': 'Intereses de Empresas',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
