# Generated by Django 5.2.13 on 2026-05-03 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Familia')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
            ],
            options={
                'verbose_name': 'Familia Profesional',
                'verbose_name_plural': 'Familias Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (Opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_cursos/', verbose_name='Imagen del Curso')),
                ('perfil_profesional', models.TextField(blank=True, null=True, verbose_name='Perfil Profesional (Opcional)')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.familiaprofesional')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
