# Generated by Django 5.2.13 on 2026-05-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('anio_egreso', models.IntegerField(verbose_name='Año de Egreso')),
                ('nombre_instructor', models.CharField(max_length=100, verbose_name='Instructor de la cursada')),
                ('telefono_principal', models.CharField(max_length=50, verbose_name='Teléfono Principal')),
                ('tiene_whatsapp', models.BooleanField(default=True, verbose_name='¿Tiene WhatsApp?')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Alternativo')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula (Si aplica)')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador (Privado)')),
                ('foto_certificado', models.ImageField(blank=True, null=True, upload_to='certificados/', verbose_name='Foto del Certificado')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresados', to='core.curso', verbose_name='Curso Realizado')),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitante', models.CharField(choices=[('empresa', 'Empresa'), ('particular', 'Particular'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Solicitante')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono de Contacto')),
                ('es_whatsapp', models.BooleanField(default=False, verbose_name='¿Es WhatsApp?')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('zona_trabajo', models.CharField(max_length=150, verbose_name='Zona del Trabajo')),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja (Planificable)'), ('MEDIA', 'Media (Próximos días)'), ('ALTA', 'Alta / Inmediata')], default='MEDIA', max_length=20, verbose_name='Nivel de Urgencia')),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del requerimiento')),
                ('estado', models.CharField(choices=[('NUEVA', 'Recibida - Sin leer'), ('REVISION', 'En Revisión'), ('CONTACTADO', 'Contacto Establecido'), ('FINALIZADA', 'Finalizada / Cerrada')], default='NUEVA', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('notas_resolucion', models.TextField(blank=True, null=True, verbose_name='Notas de Resolución (Admin)')),
                ('curso_requerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Especialidad Requerida')),
            ],
            options={
                'verbose_name': 'Solicitud de Profesional',
                'verbose_name_plural': 'Solicitudes de Profesionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
