# Generated by Django 5.2.13 on 2026-05-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_egresado_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalIndependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('descripcion_perfil', models.TextField()),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cv_profesionales/')),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profesional Independiente',
                'verbose_name_plural': 'Profesionales Independientes',
            },
        ),
    ]
