# Generated by Django 5.2.13 on 2026-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profesionalindependiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalindependiente',
            name='cursos_realizados',
            field=models.CharField(default='No especificado', help_text='Ej: Electricista Industrial, Herrero', max_length=255, verbose_name='Cursos Realizados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesionalindependiente',
            name='foto_certificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificados_autonomos/', verbose_name='Foto del Certificado (Opcional)'),
        ),
    ]
